require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommunicationDevicesController do

  # This should return the minimal set of attributes required to create a valid
  # CommunicationDevice. As you add validations to CommunicationDevice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommunicationDevicesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all communication_devices as @communication_devices" do
      communication_device = CommunicationDevice.create! valid_attributes
      get :index, {}, valid_session
      assigns(:communication_devices).should eq([communication_device])
    end
  end

  describe "GET show" do
    it "assigns the requested communication_device as @communication_device" do
      communication_device = CommunicationDevice.create! valid_attributes
      get :show, {:id => communication_device.to_param}, valid_session
      assigns(:communication_device).should eq(communication_device)
    end
  end

  describe "GET new" do
    it "assigns a new communication_device as @communication_device" do
      get :new, {}, valid_session
      assigns(:communication_device).should be_a_new(CommunicationDevice)
    end
  end

  describe "GET edit" do
    it "assigns the requested communication_device as @communication_device" do
      communication_device = CommunicationDevice.create! valid_attributes
      get :edit, {:id => communication_device.to_param}, valid_session
      assigns(:communication_device).should eq(communication_device)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommunicationDevice" do
        expect {
          post :create, {:communication_device => valid_attributes}, valid_session
        }.to change(CommunicationDevice, :count).by(1)
      end

      it "assigns a newly created communication_device as @communication_device" do
        post :create, {:communication_device => valid_attributes}, valid_session
        assigns(:communication_device).should be_a(CommunicationDevice)
        assigns(:communication_device).should be_persisted
      end

      it "redirects to the created communication_device" do
        post :create, {:communication_device => valid_attributes}, valid_session
        response.should redirect_to(CommunicationDevice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved communication_device as @communication_device" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunicationDevice.any_instance.stub(:save).and_return(false)
        post :create, {:communication_device => {  }}, valid_session
        assigns(:communication_device).should be_a_new(CommunicationDevice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommunicationDevice.any_instance.stub(:save).and_return(false)
        post :create, {:communication_device => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested communication_device" do
        communication_device = CommunicationDevice.create! valid_attributes
        # Assuming there are no other communication_devices in the database, this
        # specifies that the CommunicationDevice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommunicationDevice.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => communication_device.to_param, :communication_device => { "these" => "params" }}, valid_session
      end

      it "assigns the requested communication_device as @communication_device" do
        communication_device = CommunicationDevice.create! valid_attributes
        put :update, {:id => communication_device.to_param, :communication_device => valid_attributes}, valid_session
        assigns(:communication_device).should eq(communication_device)
      end

      it "redirects to the communication_device" do
        communication_device = CommunicationDevice.create! valid_attributes
        put :update, {:id => communication_device.to_param, :communication_device => valid_attributes}, valid_session
        response.should redirect_to(communication_device)
      end
    end

    describe "with invalid params" do
      it "assigns the communication_device as @communication_device" do
        communication_device = CommunicationDevice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunicationDevice.any_instance.stub(:save).and_return(false)
        put :update, {:id => communication_device.to_param, :communication_device => {  }}, valid_session
        assigns(:communication_device).should eq(communication_device)
      end

      it "re-renders the 'edit' template" do
        communication_device = CommunicationDevice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommunicationDevice.any_instance.stub(:save).and_return(false)
        put :update, {:id => communication_device.to_param, :communication_device => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested communication_device" do
      communication_device = CommunicationDevice.create! valid_attributes
      expect {
        delete :destroy, {:id => communication_device.to_param}, valid_session
      }.to change(CommunicationDevice, :count).by(-1)
    end

    it "redirects to the communication_devices list" do
      communication_device = CommunicationDevice.create! valid_attributes
      delete :destroy, {:id => communication_device.to_param}, valid_session
      response.should redirect_to(communication_devices_url)
    end
  end

end
